[theme]
base = "light"
primaryColor = "#1E3A8A"
backgroundColor = "#F4F6F9"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true

[browser]
gatherUsageStats = false